name: 'Send Request Action'
description: 'Send a POST request to the API with a list of pages as input'
inputs:
  pages:
    description: 'A list of strings or IDs representing the pages'
    required: true
  apiKey:
    description: 'API key for authorization'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Send POST request using curl
      run: |
        PAGE_IDS_JSON=[$(echo ${{ inputs.pages }} | sed 's/,/,/g' | sed 's/\([^,"]\+\)/"\1"/g')]
        PAYLOAD=$(echo "{\"pages\": $PAGE_IDS_JSON}")

        curl -X POST -f \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ inputs.apiKey }}" \
          -d "$PAYLOAD" \
          https://api.omnifractal.com/v1/auditWithActions
      shell: bash
