name: 'Send Request Action'
description: 'Send a POST request to the API with a list of pages as input'
inputs:
  pages:
    description: 'A list of strings or IDs representing the pages'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send POST request using curl
      run: |
        API_ENDPOINT="https://api.omnifractal.com/v1/auditWithActions"
        PAGES='${{ inputs.pages }}'
        curl -X POST -H "Content-Type: application/json" -d "{\"pages\": $PAGES}" $API_ENDPOINT
      shell: bash
