name: 'Omnifractal Audit Action'
description: 'Audit pages using Omnifractal API'
branding:
  icon: 'check'
  color: 'blue'

inputs:
  pages:
    description: 'Newline-separated string of pages to audit'
    required: true

  api_key:
    description: 'Omnifractal API key'
    required: false

outputs:
  audit_result:
    description: 'The audit result from the Omnifractal API'
    value: ${{ steps.audit_step.outputs.audit_result }}

runs:
  using: 'composite'
  steps:
    - name: 'Set execute permission for audit.sh'
      run: chmod +x audit.sh
      shell: bash

    - id: audit_step
      name: 'Audit pages using Omnifractal API'
      run: |
        echo "Running audit for pages: ${{ inputs.pages }}"
        pages_array=$(echo '${{ inputs.pages }}' | jq -R -s -c 'split("\n")')
        ./audit.sh "$pages_array"
      shell: bash
