name: 'Send Request Action'
description: 'Send a POST request to the API with a list of pages as input'
inputs:
  pages:
    description: 'A list of strings or IDs representing the pages'
    required: true
  apiKey:
    description: 'API key for authorization'
    required: true
  budgetsPath:
    description: 'Path to the Lighthouse budget file'
    required: false

runs:
  using: 'node16'
  main: 'src/index.js'
