name: Build

on: [push]

jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Send POST request using Send Request Action
      uses: faceplace/icefractal-actions@main
      with:
        pages: |
          cs7FrcGScrf28787YXcv
        apiKey: ${{ secrets.OMNIFRACTAL_TEST_PROJECT1_API_KEY }}
        budgetsPath: '.github/omnifractal/budgets.json'
        # budget: ${{ toJson(file('.github/omnifractal/budget.json')) }}
        # repository: ${{ github.repository }}
        # ref_name: ${{ github.ref_name }}
