name: My Workflow

on: [push]

env:
  PAGES: '["u4sedqsS1aFnUQRTpGqh"]'

jobs:
  make_post_request:
    runs-on: ubuntu-latest
    steps:
    - name: Send POST request
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"pages": $PAGES}' \
          https://api.omnifractal.com/v1/auditWithActions
