name: Send POST request to API

on:
  push:
    branches:
      - main

jobs:
  send_post_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send POST request using custom action
      uses: your-username/send-request-action@main
      with:
        pages: '["page1_id", "page2_id", "page3_id"]'
