name: My Workflow

on: [push]

env:
  PAGES: '["u4sedqsS1aFnUQRTpGqh"]'

jobs:
  make_post_request:
    runs-on: ubuntu-latest
    steps:
    - name: Send POST request
      run: |
        payload=$(echo "{\"pages\": $PAGES}")
        curl -X POST -f \
          -H "Content-Type: application/json" \
          -d "$payload" \
          https://api.omnifractal.com/v1/auditWithActions
