name: Send POST request to API

on:
  push:
    branches:
      - main

jobs:
  send_post_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send POST request using custom action
      uses: faceplace/icefractal-actions@main
      with:
        pages: '["u4sedqsS1aFnUQRTpGqh"]'
