name: My Workflow

on: [push]

env:
  PAGES: |
    - u4sedqsS1aFnUQRTpGqh

jobs:
  make_post_request:
    runs-on: ubuntu-latest
    steps:
    - name: Send POST request
      run: |
        pages_json="["

        while IFS= read -r line; do
          pages_json="${pages_json}\"${line}\","
        done <<< "$PAGES"

        pages_json="${pages_json%,}]"
        payload=$(echo "{\"pages\": $pages_json}")

        curl -X POST -f \
          -H "Content-Type: application/json" \
          -d "$payload" \
          https://api.omnifractal.com/v1/auditWithActions
