name: My Workflow

on: [push]

jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
    - name: Send POST request using Send Request Action
      uses: faceplace/icefractal-actions@main
      with:
        pages: u4sedqsS1aFnUQRTpGqh
        apiKey: ${{ secrets.OMNIFRACTAL_TEST_PROJECT1_API_KEY }}
        budgetPath: '${{ github.workspace }}/.github/omnifractal/budget.json'
        # repository: ${{ github.repository }}
        # ref_name: ${{ github.ref_name }}
