name: My Workflow

on: [push]

jobs:
  make_post_request:
    runs-on: ubuntu-latest
    steps:
    - name: Send POST request
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"pages": ["u4sedqsS1aFnUQRTpGqh"]}' \
          https://api.omnifractal.com/v1/auditWithActions
