name: My Workflow

on: [push]

jobs:
  make_post_request:
    runs-on: ubuntu-latest
    steps:
    - name: Send POST request
      uses: actions/http-client@v1.0.0
      with:
        url: 'https://api.omnifractal.com/v1/auditWithActions'
        method: POST
        headers: '{"Content-Type": "application/json"}'
        body: '{"pages": ["u4sedqsS1aFnUQRTpGqh"]}'
