name: My Workflow

on: [push]

env:
  PAGES: |
    - u4sedqsS1aFnUQRTpGqh

jobs:
  make_post_request:
    runs-on: ubuntu-latest
    steps:
    - name: Send POST request
      run: |
        pages_json=$(echo "$PAGES" | jq -R . | jq -s .)
        payload=$(echo "{\"pages\": $pages_json}")
        curl -X POST -f \
          -H "Content-Type: application/json" \
          -d "$payload" \
          https://api.omnifractal.com/v1/auditWithActions
